/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tacode2;
import data.user;
import javax.swing.ImageIcon;
/**
 *
 * @author User
 */
public class viewDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewDetailsPanel
     */
    user inputUser;
   String Icon = inputUser.getPhoto();
   ImageIcon photo = new ImageIcon(Icon);
    
    
    
    public viewDetailsPanel(user givenUser) {
        initComponents();
        this.inputUser = givenUser;
         populateFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        tittleLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        firstNameAnswer = new javax.swing.JLabel();
        lastNameAnswer = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        teleNumLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        majorLabel = new javax.swing.JLabel();
        ageAnswer = new javax.swing.JLabel();
        teleNumAnswer = new javax.swing.JLabel();
        emailAnswer = new javax.swing.JLabel();
        addressAnswer = new javax.swing.JLabel();
        countryAnswer = new javax.swing.JLabel();
        majorAnswer = new javax.swing.JLabel();
        cityAnswer = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        photoAnswer = new javax.swing.JLabel();
        displayField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        firstNameLabel.setText("First Name");

        tittleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tittleLabel.setText("User's Profile");

        lastNameLabel.setText("Last Name");

        cityLabel.setText("City");

        ageLabel.setText("Age");

        teleNumLabel.setText("Telephone number");

        emailLabel.setText("Email");

        addressLabel.setText("Address");

        countryLabel.setText("Country");

        majorLabel.setText("Major");

        photoLabel.setText("Photo");

        jButton1.setText("View Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNameLabel)
                                    .addComponent(lastNameLabel))
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameAnswer)
                                    .addComponent(lastNameAnswer)
                                    .addComponent(teleNumAnswer)
                                    .addComponent(countryAnswer)
                                    .addComponent(majorAnswer)
                                    .addComponent(ageAnswer)
                                    .addComponent(emailAnswer)
                                    .addComponent(addressAnswer)
                                    .addComponent(cityAnswer)
                                    .addComponent(photoAnswer)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageLabel)
                                    .addComponent(teleNumLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(addressLabel)
                                    .addComponent(countryLabel)
                                    .addComponent(cityLabel)
                                    .addComponent(majorLabel)
                                    .addComponent(photoLabel)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(53, 53, 53)
                        .addComponent(tittleLabel)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(tittleLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jButton1)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameAnswer)))
                    .addComponent(displayField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teleNumLabel)
                    .addComponent(teleNumAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLabel)
                    .addComponent(countryAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorLabel)
                    .addComponent(majorAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(photoAnswer))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       displayField.setIcon(photo);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressAnswer;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel ageAnswer;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel cityAnswer;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel countryAnswer;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel displayField;
    private javax.swing.JLabel emailAnswer;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel firstNameAnswer;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lastNameAnswer;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel majorAnswer;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JLabel photoAnswer;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel teleNumAnswer;
    private javax.swing.JLabel teleNumLabel;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        //take data from the user object and set it to the fields
        firstNameAnswer.setText(inputUser.getFirstName());
        lastNameAnswer.setText(inputUser.getLastName());
        ageAnswer.setText(inputUser.getAge());
        teleNumAnswer.setText(inputUser.getTeleNum());
        emailAnswer.setText(inputUser.getEmail());
        addressAnswer.setText(inputUser.getAddress());
        cityAnswer.setText(inputUser.getCity());
        countryAnswer.setText(inputUser.getCountry());
        majorAnswer.setText(inputUser.getMajor());
        photoAnswer.setText(inputUser.getPhoto());
       
    }
}
